import "./globals.css";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { Inter } from "next/font/google";
import React from "react";
import SessionProvider from "../component/utils/layout/sessionProvider";
import ReduxProvider from "../component/utils/layout/reduxProvider";
import { Navbar } from "../component/navbar/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body suppressHydrationWarning className={[inter.className].join(" ")}>
        <ReduxProvider>
          <SessionProvider session={session}>
            <Navbar
              isLogged={session !== null}
              name={session?.user?.name ?? undefined}
              email={session?.user?.email ?? undefined}
            />
            {children}
          </SessionProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
