name: components-update

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Print Workspace Directory
        run: | 
          echo "Workspace: $GITHUB_WORKSPACE"
      - name: format & lint
        run: |
          cd  C:\Users\clark\Documents\codes\aws\influencers\next-components\
          npm run format
          npm run lint