name: components-update

on:
  push:
    tags:
      - "*"
    branches-ignore:
      - "main"
  pull_request:
    types:
      - opened

jobs:
  pushJob:
    runs-on: self-hosted
    if: github.event_name == 'push'
    steps:
      - name: event name
        run: | 
          echo {{github.event_name}}
      - name: format & lint
        run: |
          cd  C:\Users\clark\Documents\codes\aws\influencers\next-components\
          npm run format
          npm run lint
      - name: lint success
        run: |
          cd  C:\Users\clark\Documents\codes\aws\influencers\next-components\
          git add .
          git commit -m 'edit branch v1'
          git push -u origin v1
        if: success()
      - name: lint failed
        run: |
          echo "lint failed"
        if: failure()
  pullRequestJob:
    runs-on: self-hosted
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Main repo
        run: |
          cd  C:\Users\clark\Documents\codes\aws\influencers\next-components\
          git switch main
      - name: ready to deploy
        run: |
          cd  C:\Users\clark\Documents\codes\aws\influencers\devop\
          .\cleanstatic.exe
      - name: github connect
        run: |
          cd  C:\Users\clark\Documents\codes\aws\influencers\next-components\storybook-static\
          git add .
          git commit -m 'init and clear'
          git push -u origin main
      - name: build static
        run: |
          cd  C:\Users\clark\Documents\codes\aws\influencers\next-components\
          npm run build-storybook
      - name: update new static
        run: | 
          cd  C:\Users\clark\Documents\codes\aws\influencers\next-components\storybook-static\
          git init
          git remote add origin https://github.com/clarkhao/clarkhao.github.io
          git branch -M main
          git add .
          git commit -m 'update'
          git push -u origin main
