name: components-update

on:
  push:
    tags:
      - "*"
    branches-ignore:
      - "main"
  pull_request:
    types:
      - opened
      - synchronize
      - closed

jobs:
  pushJob:
    runs-on: self-hosted
    if: github.event_name == 'push'
    steps:
      - name: event name
        run: | 
          echo {{github.event_name}}
      - name: format & lint
        run: |
          cd  C:\Users\clark\Documents\codes\aws\influencers\next-components\
          npm run format
          npm run lint
      - name: lint success
        run: |
          cd  C:\Users\clark\Documents\codes\aws\influencers\next-components\
          git add .
          git commit -m 'edit branch v1'
          git push -u origin v1
        if: success()
      - name: lint failed
        run: |
          echo "lint failed"
        if: failure()
  pullRequestJob:
    runs-on: self-hosted
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        if: github.event.action == 'opened' || github.event.action == 'synchronize'
      - name: Main repo
        run: |
          cd  C:\Users\clark\Documents\codes\aws\influencers\next-components\
          git switch main
          git pull origin main
      - name: ready to deploy
        run: |
          cd C:\Users\clark\Documents\codes\aws\influencers\next-components\storybook-static\
          git fetch
          git pull origin main
          cd  C:\Users\clark\Documents\codes\aws\influencers\devop\
          .\cleanstatic.exe
          cd C:\Users\clark\Documents\codes\aws\influencers\next-components\storybook-static\
          git add .
          git commit -m 'clear'
          git push -u origin main
          cd C:\Users\clark\Documents\codes\aws\influencers\next-components\
          npm run build-storybook
          cd C:\Users\clark\Documents\codes\aws\influencers\next-components\storybook-static\
          git fetch
          git pull origin main
          git add .
          git commit -m 'update'
          git push -u origin main
        if: github.event.action == 'closed'