name: components-update

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Print Workspace Directory
        run: | 
          echo "Workspace: $GITHUB_WORKSPACE"
      - name: git push again
        run: |
          git add .
          git commit -m 'edit branch v1'
          git push -u origin v1
      - name: format & lint
        run: |
          cd  C:\Users\clark\Documents\codes\aws\influencers\next-components\
          npm run format
          npm run lint
      - name: lint success
        run: |
          echo "lint success"
        if: success()
      - name: lint failed
        run: |
          echo "lint failed"
        if: failure()
      